
 
# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
 	- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
 	- . ~/.nvm/nvm.sh
 	- nvm install node
 	- node -e "console.log('Running Node.js ' + process.version)"
  pre_build:
    commands:
 	- echo "creating the folder"
 	- mkdir /home/ec2-user/node
      	- npm init --yes
      	- npm install express
      	- npm install mongodb
 	- npm install nodemon
  build:
    commands:
     	- /home/ec2-user/node
      	- node app.js
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - App.js
    - node_modules
    - package.json
    - package-lock.json
